/**
 * ExplorePublicPageService — renders a public, shareable HTML page for a published
 * explainer bundle. Designed to be served without authentication at /explore/:owner/:repo.
 *
 * The page follows the "comprehension arc" derived from explainmyrepo.isovision.ai
 * and Egonex-AI/Understand-Anything research, adapted to the data djimitflo already
 * produces (bundle manifest, sections, facts, graph summary, health meters).
 */

import Database from "better-sqlite3";
import type {
  ExplainerBundleContent,
  ExplainerManifest,
  GraphSummary,
  HealthMeter,
} from "@djimitflo/shared";
import { BundleBuilder } from "./bundle-builder";

export interface RenderPageInput {
  owner: string;
  repo: string;
  bundleContent: ExplainerBundleContent;
  baseUrl: string;
}

export interface RenderPageResult {
  html: string;
  status: "ok" | "not_found" | "unpublished";
}

export class ExplorePublicPageService {
  constructor(private db: Database.Database) {}

  findPublishedBundle(owner: string, repo: string): ExplainerBundleContent | null {
    const fullName = `${owner}/${repo}`;

    // Pick the newest PUBLISHED bundle for this repository.
    const row = this.db
      .prepare(
        `
        SELECT b.id
        FROM explainer_bundles b
        JOIN explainer_tasks t ON t.id = b.task_id
        LEFT JOIN discovered_repositories dr ON dr.id = t.discovered_repository_id
        WHERE (dr.full_name = ? OR (t.discovered_repository_id IS NULL AND t.remote_url IN (?, ?)))
          AND b.status = 'published'
        ORDER BY b.created_at DESC
        LIMIT 1
      `
      )
      .get(fullName, `https://github.com/${fullName}`, `https://github.com/${fullName}.git`) as { id: string } | undefined;

    if (!row) return null;

    const builder = new BundleBuilder(this.db);
    try {
      return builder.loadBundleContent(row.id);
    } catch {
      return null;
    }
  }

  render({ owner, repo, bundleContent, baseUrl }: RenderPageInput): RenderPageResult {
    const manifest = bundleContent.manifest;
    const graph = bundleContent.graph_summary;
    const sections = bundleContent.sections || {};
    const facts = bundleContent.facts || [];

    const repoUrl = manifest.repository_url || `https://github.com/${owner}/${repo}`;
    const pageUrl = `${baseUrl}/explore/${owner}/${repo}`;
    const title = `${manifest.repository_full_name} · Djimit Explore`;
    const tagline = this.extractTagline(sections.overview);
    const health = this.parseHealth(sections.health);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${this.escape(title)}</title>
  <meta name="description" content="${this.escape(tagline)}" />
  <meta property="og:title" content="${this.escape(title)}" />
  <meta property="og:description" content="${this.escape(tagline)}" />
  <meta property="og:url" content="${this.escape(pageUrl)}" />
  <meta property="og:type" content="website" />
  <meta property="og:image" content="${this.escape(`${pageUrl}/opengraph.svg`)}" />
  <meta name="twitter:card" content="summary_large_image" />
  <link rel="canonical" href="${this.escape(pageUrl)}" />
  <style>
    :root { color-scheme: dark; }
    * { box-sizing: border-box; }
    body { margin: 0; background: #020617; color: #f1f5f9; font-family: system-ui, sans-serif; }
    main, footer > div { width: min(100% - 3rem, 64rem); margin: 0 auto; }
    main { padding: 3rem 0; }
    section { padding: 1.5rem; margin-bottom: 2rem; border: 1px solid #1e293b; border-radius: 1rem; background: #0f172a; }
    h1 { font-size: clamp(2rem, 5vw, 3rem); }
    a { color: #818cf8; }
    footer { padding: 2rem 0; border-top: 1px solid #1e293b; }
    .prose h2 { font-size: 1.5rem; font-weight: 700; margin-top: 2rem; margin-bottom: 0.75rem; color: #f8fafc; }
    .prose h3 { font-size: 1.25rem; font-weight: 600; margin-top: 1.5rem; margin-bottom: 0.5rem; color: #e2e8f0; }
    .prose p { margin-bottom: 0.75rem; line-height: 1.7; color: #cbd5e1; }
    .prose ul { list-style: disc; padding-left: 1.25rem; margin-bottom: 1rem; color: #cbd5e1; }
    .prose li { margin-bottom: 0.25rem; }
    .prose a { color: #818cf8; text-decoration: underline; }
  </style>
</head>
<body class="min-h-screen">
  <main class="mx-auto max-w-5xl px-6 py-12">
    ${this.renderHero(manifest, tagline, health)}
    ${this.renderHealthPanel(health)}
    ${this.renderArchitecture(graph)}
    ${this.renderSections(sections)}
    ${this.renderFacts(facts)}
    ${this.renderProvenance(manifest, repoUrl)}
  </main>

  <footer class="border-t border-slate-800 bg-slate-950 py-8">
    <div class="mx-auto max-w-5xl px-6 text-sm text-slate-500">
      <p>Generated by Djimit Explore from commit ${manifest.source_commit.slice(0, 7)} · ${new Date(manifest.generated_at).toLocaleString()}</p>
      <p class="mt-2">AI-generated summary. Verify claims against the source repository before acting on them.</p>
      <p class="mt-2"><a href="${this.escape(this.safeHttpUrl(repoUrl))}" class="text-indigo-400 hover:text-indigo-300">View on GitHub</a> · <a href="${this.escape(pageUrl)}/llms.txt" class="text-indigo-400 hover:text-indigo-300">llms.txt</a></p>
    </div>
  </footer>
</body>
</html>`;

    return { html, status: "ok" };
  }

  private renderHero(
    manifest: ExplainerManifest,
    tagline: string,
    health: { overall: number | null; meters: HealthMeter[] },
  ): string {
    const score = manifest.openmythos_score ?? null;
    const trust = score ?? 0;
    const trustLabel = trust >= 85 ? "Verified" : trust >= 60 ? "Review" : "Early";
    const trustColor = trust >= 85 ? "text-emerald-400" : trust >= 60 ? "text-amber-400" : "text-rose-500";
    const repoUrl = manifest.repository_url;

    return `
    <section class="relative overflow-hidden rounded-2xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-950 p-8 md:p-12 mb-12">
      <div class="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-indigo-500/10 blur-3xl"></div>
      <div class="relative z-10">
        <p class="mb-2 text-sm font-medium tracking-wider text-indigo-400 uppercase">Djimit Explore</p>
        <h1 class="text-3xl font-bold text-slate-100 md:text-5xl">${this.escape(manifest.repository_full_name)}</h1>
        <p class="mt-3 max-w-2xl text-lg text-slate-400">${this.escape(tagline)}</p>

        <div class="mt-8 flex flex-wrap items-center gap-6">
          ${score !== null ? `
          <div class="flex items-center gap-3 rounded-xl border border-slate-700 bg-slate-800/50 px-4 py-3" title="OpenMythos trust score: ${trust.toFixed(1)} / 100">
            <div class="text-2xl font-bold ${trustColor}">${trust.toFixed(0)}</div>
            <div class="text-xs text-slate-400">
              <div class="font-medium text-slate-200">${trustLabel}</div>
              <div>OpenMythos</div>
            </div>
          </div>` : ""}

          ${health.overall !== null ? `
          <div class="flex items-center gap-3 rounded-xl border border-slate-700 bg-slate-800/50 px-4 py-3">
            <svg viewBox="0 0 36 36" class="h-10 w-10 -rotate-90">
              <path class="fill-none stroke-slate-700" stroke-width="4" d="M18 2a16 16 0 1 1 0 32 16 16 0 1 1 0-32" />
              <path class="fill-none stroke-indigo-500" stroke-width="4" stroke-dasharray="${health.overall}, 100" d="M18 2a16 16 0 1 1 0 32 16 16 0 1 1 0-32" />
            </svg>
            <div class="text-xs text-slate-400">
              <div class="font-medium text-slate-200">${health.overall}/100</div>
              <div>Health</div>
            </div>
          </div>` : ""}

          <a href="${this.escape(this.safeHttpUrl(repoUrl))}" target="_blank" rel="noopener noreferrer" class="rounded-xl bg-indigo-500 px-5 py-3 text-sm font-medium text-white transition hover:bg-indigo-400">View on GitHub</a>
        </div>
      </div>
    </section>`;
  }

  private renderHealthPanel(health: { overall: number | null; meters: HealthMeter[] }): string {
    if (health.meters.length === 0 && health.overall === null) return "";
    const meterClass = (status: HealthMeter["status"]) => {
      switch (status) {
        case "good":
          return "bg-emerald-500";
        case "warning":
          return "bg-amber-400";
        case "critical":
          return "bg-rose-500";
        default:
          return "bg-slate-500";
      }
    };

    return `
    <section class="rounded-2xl border border-slate-800 bg-slate-900 p-6 md:p-8 mb-12">
      <h2 class="text-xl font-semibold text-slate-100">Repository health</h2>
      ${health.overall !== null ? `<div class="mt-4 flex items-center gap-4"><div class="text-3xl font-bold text-slate-100">${health.overall}</div><div class="text-sm text-slate-400">Overall health score out of 100</div></div>` : ""}
      <div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        ${health.meters.map((m) => `
          <div class="rounded-xl border border-slate-700 bg-slate-800/40 p-4">
            <div class="flex items-center justify-between">
              <span class="text-sm font-medium text-slate-300">${this.escape(m.label)}</span>
              <span class="inline-block h-2 w-2 rounded-full ${meterClass(m.status)}" aria-hidden="true"></span>
            </div>
            <div class="mt-2 text-lg font-semibold text-slate-100">${m.score}/100</div>
            ${m.recommendation ? `<p class="mt-1 text-xs text-slate-400">${this.escape(m.recommendation)}</p>` : ""}
          </div>
        `).join("")}
      </div>
    </section>`;
  }

  private renderArchitecture(graph: GraphSummary): string {
    if (!graph || graph.communities.length === 0) return "";
    const width = 800;
    const height = 400;
    const cx = width / 2;
    const cy = height / 2;
    const nodes = graph.communities.map((c, i) => ({
      id: `c-${i}`,
      label: c.name,
      x: cx + Math.cos((2 * Math.PI * i) / Math.max(graph.communities.length, 1) - Math.PI / 2) * 200,
      y: cy + Math.sin((2 * Math.PI * i) / Math.max(graph.communities.length, 1) - Math.PI / 2) * 160,
      size: Math.max(20, Math.min(60, c.size * 2)),
    }));

    return `
    <section class="rounded-2xl border border-slate-800 bg-slate-900 p-6 md:p-8 mb-12">
      <h2 class="text-xl font-semibold text-slate-100">Architecture</h2>
      <p id="architecture-summary" class="mt-1 text-sm text-slate-400">Constellation view of detected code communities.</p>
      <svg viewBox="0 0 ${width} ${height}" class="mt-4 w-full" role="img" aria-describedby="architecture-summary">
        <rect width="${width}" height="${height}" fill="#0f172a" rx="16" />
        ${nodes.map((n) => `
          <circle cx="${n.x}" cy="${n.y}" r="${n.size}" fill="#6366f1" opacity="0.8" />
          <text x="${n.x}" y="${n.y + 5}" text-anchor="middle" fill="#f1f5f9" font-size="12" font-weight="600">${this.escape(n.label.slice(0, 3).toUpperCase())}</text>
          <text x="${n.x}" y="${n.y + n.size + 18}" text-anchor="middle" fill="#94a3b8" font-size="11">${this.escape(n.label)}</text>
        `).join("")}
      </svg>
      <div class="mt-4 flex flex-wrap gap-4 text-xs text-slate-400">
        <div class="flex items-center gap-2"><span class="h-3 w-3 rounded-full bg-indigo-500"></span><span>Community</span></div>
      </div>
    </section>`;
  }

  private renderSections(sections: Record<string, string>): string {
    const order = ["overview", "architecture", "health", "dependencies", "components", "api", "flows", "deployment", "security", "testing", "governance"];
    const rendered = order
      .filter((key) => sections[key])
      .map((key) => {
        const markdownHtml = this.markdownToHtml(sections[key]);
        return `
          <section class="mb-12">
            <div class="prose max-w-none">${markdownHtml}</div>
          </section>`;
      })
      .join("");

    return rendered ? `<div class="mb-12">${rendered}</div>` : "";
  }

  private renderFacts(facts: ExplainerBundleContent["facts"]): string {
    if (!facts.length) return "";
    return `
    <section class="rounded-2xl border border-slate-800 bg-slate-900 p-6 md:p-8 mb-12">
      <h2 class="text-xl font-semibold text-slate-100">Grounded facts</h2>
      <ul class="mt-4 space-y-2 text-sm text-slate-300">
        ${facts.map((f) => `<li>• ${this.escape(f.claim)} <span class="text-slate-500">— ${this.escape(f.source_ref)}</span></li>`).join("")}
      </ul>
    </section>`;
  }

  private renderProvenance(manifest: ExplainerManifest, repoUrl: string): string {
    return `
    <section class="rounded-2xl border border-slate-800 bg-slate-900 p-6 md:p-8 mb-12">
      <h2 class="text-xl font-semibold text-slate-100">Provenance</h2>
      <p class="mt-2 text-sm text-slate-400">
        This page was generated from <a href="${this.escape(this.safeHttpUrl(repoUrl))}" class="text-indigo-400 hover:text-indigo-300">${this.escape(manifest.repository_full_name)}</a>
        at commit <code class="rounded bg-slate-800 px-1.5 py-0.5 text-slate-200">${manifest.source_commit.slice(0, 7)}</code>.
      </p>
    </section>`;
  }

  private extractTagline(overviewMarkdown?: string): string {
    if (!overviewMarkdown) return "An AI-generated explainer for this repository.";
    const lines = overviewMarkdown.split("\n").map((l) => l.trim()).filter((l) => l.length > 0);
    // Skip the title line; take the first substantive sentence after it.
    const firstBody = lines.find((l, i) => i > 0 && !l.startsWith("#") && l.length > 20) || "";
    if (firstBody) return firstBody.replace(/\.$/, "").trim();
    const title = lines[0]?.replace(/^#\s*/, "").trim() || "";
    return title || "An AI-generated explainer for this repository.";
  }

  private parseHealth(healthMarkdown?: string): { overall: number | null; meters: HealthMeter[] } {
    if (!healthMarkdown) return { overall: null, meters: [] };
    const overallMatch = healthMarkdown.match(/Overall score[:\s]+(\d+)/);
    const overall = overallMatch ? Number(overallMatch[1]) : null;
    return { overall, meters: [] };
  }

  private markdownToHtml(markdown: string): string {
    // Minimal safe markdown-to-HTML transform for the generated sections.
    return markdown
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/^#\s+(.*)$/gm, "<h2>$1</h2>")
      .replace(/^##\s+(.*)$/gm, "<h3>$1</h3>")
      .replace(/^###\s+(.*)$/gm, "<h4>$1</h4>")
      .replace(/^\s*-\s+(.*)$/gm, "<li>$1</li>")
      .replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>")
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_match, label: string, href: string) => {
        const safeHref = this.safeMarkdownUrl(href);
        return safeHref ? `<a href="${safeHref}" target="_blank" rel="noopener noreferrer">${label}</a>` : label;
      })
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.*?)\*/g, "<em>$1</em>")
      .split("\n\n")
      .map((block) => {
        if (block.startsWith("<") && !block.startsWith("<a ")) return block;
        return `<p>${block}</p>`;
      })
      .join("\n");
  }

  private escape(text: string | number | null | undefined): string {
    if (text === null || text === undefined) return "";
    return String(text)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  private safeHttpUrl(value: string): string {
    try {
      const url = new URL(value);
      return url.protocol === "https:" || url.protocol === "http:" ? url.toString() : "#";
    } catch {
      return "#";
    }
  }

  private safeMarkdownUrl(value: string): string | null {
    if (value.startsWith("#") || /^\/(?!\/)/.test(value)) return this.escape(value);
    const safe = this.safeHttpUrl(value);
    return safe === "#" ? null : this.escape(safe);
  }
}
