import { randomUUID } from 'crypto';
import fs from 'fs';
import path from 'path';
import type { Database } from 'better-sqlite3';
import { KnowledgeRuntimeService } from './knowledge-runtime-service';
import type { JudgeVerdict, ExpertAnswer } from './judge-service';

export class OkfKnowledgeUpdater {
  private okfBase: string;

  constructor(private db: Database) {
    this.okfBase = KnowledgeRuntimeService.resolveCanonicalOkfBase({ allowMissing: true });

    this.db.exec(`
      CREATE TABLE IF NOT EXISTS okf_knowledge_updates (
        id TEXT PRIMARY KEY,
        topic TEXT NOT NULL,
        action TEXT NOT NULL,
        concept_path TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      )
    `);
  }

  async updateFromVerdict(topic: string, answers: ExpertAnswer[], verdict: JudgeVerdict): Promise<boolean> {
    if (verdict.verification_status === 'contradicted' || verdict.verification_status === 'unverifiable') {
      return false;
    }

    try {
      const content = this.buildConceptContent(topic, answers, verdict);
      const slug = topic.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 50);
      const conceptPath = path.join(this.okfBase, 'concepts', `${slug}.md`);

      const existing = this.findExistingConcept(topic);
      if (existing) {
        this.updateConcept(existing, content, verdict);
      } else {
        this.createConcept(conceptPath, content);
      }

      this.db.prepare(`
        INSERT INTO okf_knowledge_updates (id, topic, action, concept_path)
        VALUES (?, ?, ?, ?)
      `).run(randomUUID(), topic, existing ? 'updated' : 'created', conceptPath);

      return true;
    } catch {
      return false;
    }
  }

  getUpdateHistory(limit: number = 20): Array<{ id: string; topic: string; action: string; concept_path: string | null; created_at: string }> {
    return this.db.prepare('SELECT * FROM okf_knowledge_updates ORDER BY created_at DESC LIMIT ?').all(limit) as Array<{
      id: string; topic: string; action: string; concept_path: string | null; created_at: string;
    }>;
  }

  private findExistingConcept(topic: string): string | null {
    if (!this.okfBase || !fs.existsSync(this.okfBase)) return null;

    const conceptsDir = path.join(this.okfBase, 'concepts');
    if (!fs.existsSync(conceptsDir)) return null;

    const files = fs.readdirSync(conceptsDir).filter(f => f.endsWith('.md'));
    const slug = topic.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 50);

    for (const file of files) {
      if (file.includes(slug) || slug.includes(file.replace('.md', ''))) {
        return path.join(conceptsDir, file);
      }
    }

    return null;
  }

  private createConcept(conceptPath: string, content: string): void {
    const dir = path.dirname(conceptPath);
    try { fs.mkdirSync(dir, { recursive: true }); } catch { /* best-effort */ }
    fs.writeFileSync(conceptPath, content, 'utf8');
  }

  private updateConcept(conceptPath: string, content: string, verdict: JudgeVerdict): void {
    try {
      const existing = fs.readFileSync(conceptPath, 'utf8');
      const updated = existing + `\n\n## Update ${new Date().toISOString().slice(0, 10)}\n\nConfidence: ${verdict.confidence.toFixed(2)}\n\n${content}`;
      fs.writeFileSync(conceptPath, updated, 'utf8');
    } catch { /* best-effort */ }
  }

  private buildConceptContent(topic: string, answers: ExpertAnswer[], verdict: JudgeVerdict): string {
    const sources = answers.map(a => ({
      domain: a.domain,
      source: a.source,
      url: (a.metadata?.url as string) || '',
      title: (a.metadata?.title as string) || '',
    }));

    const frontmatter = [
      '---',
      `type: Concept`,
      `title: "${topic}"`,
      `confidence: ${verdict.confidence.toFixed(2)}`,
      `verification: ${verdict.verification_status}`,
      `domains: [${answers.map(a => a.domain).join(', ')}]`,
      `sources: [${sources.filter(s => s.url).map(s => s.url).join(', ')}]`,
      `updated: ${new Date().toISOString()}`,
      '---',
    ].join('\n');

    const body = [
      `# ${topic}`,
      '',
      '## Summary',
      '',
      `This concept was automatically generated by DjimFlo Expert Swarm.`,
      '',
      '## Domain Knowledge',
      '',
      ...answers.map(a => `### ${a.domain}\n\n${a.content}\n`),
      '',
      '## Sources',
      '',
      ...sources.filter(s => s.url).map(s => `- ${s.title || s.source}: ${s.url}`),
      '',
      '## Verification',
      '',
      `- Score: ${verdict.score}/100`,
      `- Confidence: ${verdict.confidence.toFixed(2)}`,
      `- Status: ${verdict.verification_status}`,
      `- Contradictions: ${verdict.contradictions.length}`,
    ].join('\n');

    return `${frontmatter}\n\n${body}\n`;
  }
}
